
function fft_core_config(this_block)

  % Revision History:
  %
  %   31-Dec-2015  (12:45 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/ayoung/Work/projects/Project8/roach2_dev/master/fft_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('fft_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
%   this_block.tagAsCombinational;

  this_block.addSimulinkInport('sync_in');
  this_block.addSimulinkInport('shift');
  this_block.addSimulinkInport('din0_c');
  this_block.addSimulinkInport('din1_c');
  
  this_block.addSimulinkOutport('sync_out');
  this_block.addSimulinkOutport('dout0_c');
  this_block.addSimulinkOutport('dout1_c');
  this_block.addSimulinkOutport('fft_of');

  dout0_c_port = this_block.port('dout0_c');
  dout0_c_port.setType('UFix_50_0');
  dout1_c_port = this_block.port('dout1_c');
  dout1_c_port.setType('UFix_50_0');
  fft_of_port = this_block.port('fft_of');
  fft_of_port.setType('Bool');
  fft_of_port.useHDLVector(false);
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('din0_c').width ~= 50);
      this_block.setError('Input data type for port "din0_c" must have width=50.');
    end

    if (this_block.port('din1_c').width ~= 50);
      this_block.setError('Input data type for port "din1_c" must have width=50.');
    end

    if (this_block.port('shift').width ~= 13);
      this_block.setError('Input data type for port "shift" must have width=13.');
    end

    if (this_block.port('sync_in').width ~= 1);
      this_block.setError('Input data type for port "sync_in" must have width=1.');
    end

    this_block.port('sync_in').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('fft_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

